import {
  Box, Milk, CupSoda, Wheat, Package, Soup, Croissant, Utensils, Wrench, Hammer,
  Droplet, Scissors, Sparkles, Shirt, Footprints, Watch, Cpu, Smartphone, Laptop,
  Plug, Battery, Pill, Syringe, Stethoscope, Zap, Palette, Settings, Shield,
  Brush, Flower2, ShoppingBag, Gem, Scroll, Cable, Headphones, Refrigerator,
  FlaskConical, Bandage, Baby, Shapes, ChefHat, ShoppingBasket, type LucideIcon,
} from 'lucide-react'

// Maps a business_categories.icon key (see CURATED_ICONS in
// src/lib/categories.ts) to the Lucide component that renders it.
export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  'box': Box,
  'milk': Milk,
  'cup-soda': CupSoda,
  'wheat': Wheat,
  'package': Package,
  'soup': Soup,
  'croissant': Croissant,
  'utensils': Utensils,
  'wrench': Wrench,
  'hammer': Hammer,
  'droplet': Droplet,
  'scissors': Scissors,
  'sparkles': Sparkles,
  'shirt': Shirt,
  'footprints': Footprints,
  'watch': Watch,
  'cpu': Cpu,
  'smartphone': Smartphone,
  'laptop': Laptop,
  'plug': Plug,
  'battery': Battery,
  'pill': Pill,
  'syringe': Syringe,
  'stethoscope': Stethoscope,
  'zap': Zap,
  'palette': Palette,
  'settings': Settings,
  'shield': Shield,
  'brush': Brush,
  'flower-2': Flower2,
  'shopping-bag': ShoppingBag,
  'gem': Gem,
  'scroll': Scroll,
  'cable': Cable,
  'headphones': Headphones,
  'refrigerator': Refrigerator,
  'flask-conical': FlaskConical,
  'bandage': Bandage,
  'baby': Baby,
  'shapes': Shapes,
  'chef-hat': ChefHat,
  'shopping-basket': ShoppingBasket,
}
