import {
  Box, Milk, CupSoda, Wheat, Package, Soup, Croissant, Utensils, Wrench, Hammer,
  Droplet, Scissors, Sparkles, Shirt, Footprints, Watch, Cpu, Smartphone, Laptop,
  Plug, Battery, Pill, Syringe, Stethoscope, Zap, Palette, Settings, Shield,
  Brush, Flower2, ShoppingBag, Gem, Scroll, Cable, Headphones, Refrigerator,
  FlaskConical, Bandage, Baby, Shapes, ChefHat, ShoppingBasket, BrickWall,
  Layers, Construction, Grid3x3, DoorOpen, PaintBucket, Mountain, Disc, Car,
  Sprout, Shovel, PawPrint, Sofa, Bed, TreePine, Umbrella, BookOpen, Pencil,
  Backpack, Paintbrush, Printer, Wifi, Wallet, BatteryCharging, Flame, Sandwich,
  Briefcase, type LucideIcon,
} from 'lucide-react'

// Maps a business_categories.icon key (see CURATED_ICONS in
// src/lib/categories.ts) to the Lucide component that renders it.
export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  'box': Box,
  'milk': Milk,
  'cup-soda': CupSoda,
  'wheat': Wheat,
  'package': Package,
  'soup': Soup,
  'croissant': Croissant,
  'utensils': Utensils,
  'wrench': Wrench,
  'hammer': Hammer,
  'droplet': Droplet,
  'scissors': Scissors,
  'sparkles': Sparkles,
  'shirt': Shirt,
  'footprints': Footprints,
  'watch': Watch,
  'cpu': Cpu,
  'smartphone': Smartphone,
  'laptop': Laptop,
  'plug': Plug,
  'battery': Battery,
  'pill': Pill,
  'syringe': Syringe,
  'stethoscope': Stethoscope,
  'zap': Zap,
  'palette': Palette,
  'settings': Settings,
  'shield': Shield,
  'brush': Brush,
  'flower-2': Flower2,
  'shopping-bag': ShoppingBag,
  'gem': Gem,
  'scroll': Scroll,
  'cable': Cable,
  'headphones': Headphones,
  'refrigerator': Refrigerator,
  'flask-conical': FlaskConical,
  'bandage': Bandage,
  'baby': Baby,
  'shapes': Shapes,
  'chef-hat': ChefHat,
  'shopping-basket': ShoppingBasket,
  'brick-wall': BrickWall,
  'layers': Layers,
  'construction': Construction,
  'grid-3x3': Grid3x3,
  'door-open': DoorOpen,
  'paint-bucket': PaintBucket,
  'mountain': Mountain,
  'disc': Disc,
  'car': Car,
  'sprout': Sprout,
  'shovel': Shovel,
  'paw-print': PawPrint,
  'sofa': Sofa,
  'bed': Bed,
  'tree-pine': TreePine,
  'umbrella': Umbrella,
  'book-open': BookOpen,
  'pencil': Pencil,
  'backpack': Backpack,
  'paintbrush': Paintbrush,
  'printer': Printer,
  'wifi': Wifi,
  'wallet': Wallet,
  'battery-charging': BatteryCharging,
  'flame': Flame,
  'sandwich': Sandwich,
  'briefcase': Briefcase,
}
